language: go

go:
  - 1.7

# magic word to use faster/newer container-based architecture
sudo: false

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - go install
  - go vet

  # Note that unfortunately Golint doesn't work like other Go commands: it only
  # takes only a single argument at a time and expects that each is the name of a
  # local directory (as opposed to a package).
  #
  # The exit 255 trick ensures that xargs will actually bubble a failure back up
  # to the entire command.
  - go list ./... | egrep -v '/vendor/' | sed "s|^github\.com/brandur/rserve|.|" | xargs -I{} -n1 sh -c '$GOPATH/bin/golint -set_exit_status {} || exit 255'

  - scripts/check_gofmt.sh

notifications:
  email:
    on_success: never
